# Generated by Django 4.2.17 on 2025-01-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('accepted', 'прийнято'), ('rejected', 'відхилено'), ('pending', 'очікується')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
