# Generated by Django 4.2.17 on 2025-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_page', '0005_alter_only_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
